spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: "update"
  datasource:
    url: "jdbc:mariadb://localhost:3306/api_db"
    username: "ncuy0110"
    password: "Uy050770@"
    driver-class-name: "org.mariadb.jdbc.Driver"
  #spring.jpa.show-sql: true
  mail:
    host: "sandbox.smtp.mailtrap.io"
    port: 2525
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
    username: 05ce9a5b54dc70
    password: d0970a2a657f3c

api:
  access:
    secretKey: "955b46b40b5e48c9896db94aaf9fc0cb955b46b40b5e48c9896db94aaf9fc0cb955b46b40b5e48c9896db94aaf9fc0cb955b46b40b5e48c9896db94aaf9fc0c955b46b40b5e48c9896db94aaf9fc0cbb"
    expirationMs: 86400000 # ~1days
  refresh:
    secretKey: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    expirationMs: 2592000000 #30 days



working:
  days: "MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY"
  time:
    start: "0800"
    end: "1730"

